apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skyops-agent.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skyops-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  SKYOPS_CLUSTER_ID: {{ .Values.clusterId | quote }}
  SKYOPS_AGENT_TOKEN: {{ .Values.agentToken | quote }}
  SKYOPS_SERVER_URL: {{ .Values.serverUrl | quote }}
